# Generated by Django 4.1.7 on 2023-03-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_experience_details_page_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='oraganization',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
