# Generated by Django 4.1.7 on 2023-03-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_users_oraganization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='oraganization',
        ),
        migrations.AddField(
            model_name='users',
            name='organization',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
