# Generated by Django 4.1.7 on 2023-03-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_users_oraganization_users_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
