# Generated by Django 4.1.7 on 2023-03-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_users_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='key_skills',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default=1000, max_length=100),
            preserve_default=False,
        ),
    ]
