# Generated by Django 4.1.7 on 2023-03-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_team_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
    ]
