# Generated by Django 4.1.7 on 2023-03-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_job_key_skills_job_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEVICE',
            fields=[
                ('MAC_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('AUTH_TOKEN', models.CharField(max_length=100)),
            ],
        ),
    ]
